/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pharmacy.management.system;

/**
 *
 * @author N A N A
 */
import doe.ConnectionProvider;
import javax.swing.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Properties;
public class AddMedicine extends javax.swing.JFrame {

    /**
     * Creates new form AddMedicine
     */
    public String numberPattern="[0-9]*$";


    public AddMedicine() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLabel3 = new javax.swing.JLabel();
        txtDrugID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDrugType = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDrugManufacture = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtManufactureDate = new javax.swing.JTextField();
        txtExpireDate = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("ADD Medicine");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 370, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1113, 10));
        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("Drug Manufacture: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 140, -1));

        txtDrugID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDrugIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtDrugID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 220, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("Stock:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        txtStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockActionPerformed(evt);
            }
        });
        getContentPane().add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 220, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("Price per Unit:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 130, -1));

        txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPriceKeyReleased(evt);
            }
        });
        getContentPane().add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 160, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setText("Drug Type:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 80, -1));
        getContentPane().add(txtDrugType, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 170, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 51));
        jLabel8.setText("Drug ID:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 90, -1));
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 220, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 51));
        jLabel9.setText(" Name:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 100, -1));

        txtDrugManufacture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDrugManufactureActionPerformed(evt);
            }
        });
        getContentPane().add(txtDrugManufacture, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 220, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 51));
        jLabel10.setText("Manfucture Date:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, -1, -1));
        getContentPane().add(txtManufactureDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 170, -1));
        getContentPane().add(txtExpireDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 170, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 51));
        jLabel11.setText("Expire Date:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 100, -1));

        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/square-crossmark-red-button-close-exit-design-vector.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, 60, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background1.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDrugIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDrugIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDrugIDActionPerformed

    private void txtStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockActionPerformed

    private void txtPriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtPriceKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String drugID=txtDrugID.getText();
      String name=txtName.getText();
      String DrugManufacture=txtDrugManufacture.getText();
      String stock=txtStock.getText();
      String price=txtPrice.getText();
      String drugType=txtDrugType.getText();
      String ManufactureDate=txtManufactureDate.getText();
      String ExpireDate=txtExpireDate.getText();
      
        
      if(drugID.equals("")){
          JOptionPane.showMessageDialog(null, "drug ID field is required");
      }else if(name.equals("")){
          JOptionPane.showMessageDialog(null, "Name field is required");
      }else if(DrugManufacture.equals("")){
          JOptionPane.showMessageDialog(null, "drugManufacture field is required");
      }else if(stock.equals("")){
          JOptionPane.showMessageDialog(null, "stock field is required");
      }else if(!stock.matches(numberPattern)){
          JOptionPane.showMessageDialog(null, "stock field is invalid");
      }else if(price.equals("")){
          JOptionPane.showMessageDialog(null, "Price field is required");
      }else if(!price.matches(numberPattern)){
          JOptionPane.showMessageDialog(null, "Price field is invalid");
      }else if(drugType.equals("")){
           JOptionPane.showMessageDialog(null, "Drug Type field is required");
//     }else if(!ManufactureDate.matches(date)){
//          JOptionPane.showMessageDialog(null, "ManufactureDate field is invalid");
     }
      else if(ManufactureDate.equals("")){
          JOptionPane.showMessageDialog(null, "Manufacture date field is required"); 
//      }else if(!ExpireDate.matches(date)){
//           JOptionPane.showMessageDialog(null, "ExpireDate field is invalid");
   }
      else if(ExpireDate.equals("")){
           JOptionPane.showMessageDialog(null, "Expire date field is required");
          
      }
      else{
          try{
            
           Connection con=ConnectionProvider.getCon();
          PreparedStatement ps=con.prepareStatement("insert into medicine (drugID,name,DrugManufacture,stock,price,drugType,ManufactureDate,ExpireDate)values(?,?,?,?,?,?,?,?)");
          ps.setString(1,drugID);
          ps.setString(2,name);
          ps.setString(3,DrugManufacture);
          ps.setString(4,stock);
          ps.setString(5,price);
          ps.setString(6,drugType);
          ps.setString(7,ManufactureDate);
          ps.setString(8,ExpireDate);
          ps.executeUpdate();
          JOptionPane.showMessageDialog(null,"Medicine Added Successfully");
          setVisible(false);
          new AddMedicine().setVisible(true);
          }
          catch(Exception e){
              JOptionPane.showMessageDialog(null, e);
          }
      }

    
    

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtDrugManufactureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDrugManufactureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDrugManufactureActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMedicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtDrugID;
    private javax.swing.JTextField txtDrugManufacture;
    private javax.swing.JTextField txtDrugType;
    private javax.swing.JTextField txtExpireDate;
    private javax.swing.JTextField txtManufactureDate;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
