/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pharmacy.management.system;

import doe.ConnectionProvider;
import javax.swing.JOptionPane;
import java.sql.*;
/**
 *
 * @author N A N A
 */
public class Profile extends javax.swing.JFrame {
    public String mobileNumberPattern="^[0-9]*$";
    private String username="";
    
    /**
     * Creates new form Profile
     */
    public Profile() {
        initComponents();
    }
    public Profile(String tempUsername) {
        initComponents();
        username=tempUsername;
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        lUsername = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtLName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtmanager = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtStreet = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtMobileNumber = new javax.swing.JTextField();
        txtZone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/20589868_1.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Profile");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 140, 50));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/square-crossmark-red-button-close-exit-design-vector.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 0, 60, 50));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1110, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        lUsername.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lUsername.setForeground(new java.awt.Color(0, 0, 51));
        lUsername.setText("Username");
        getContentPane().add(lUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("Last Name:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, -1, -1));

        txtLName.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtLName.setForeground(new java.awt.Color(0, 0, 51));
        txtLName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 200, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setText("First Name:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        txtFName.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtFName.setForeground(new java.awt.Color(0, 0, 51));
        txtFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 200, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 51));
        jLabel7.setText("Middle Name:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, -1));

        txtMName.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtMName.setForeground(new java.awt.Color(0, 0, 51));
        getContentPane().add(txtMName, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 200, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 51));
        jLabel8.setText("Manager_ID:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, -1, -1));

        txtmanager.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtmanager.setForeground(new java.awt.Color(0, 0, 51));
        txtmanager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmanagerActionPerformed(evt);
            }
        });
        getContentPane().add(txtmanager, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, 200, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 51));
        jLabel9.setText("Street:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, -1, -1));

        txtStreet.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtStreet.setForeground(new java.awt.Color(0, 0, 51));
        getContentPane().add(txtStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 200, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 51));
        jLabel10.setText("Zone:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, -1, -1));
        getContentPane().add(txtMobileNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, 200, -1));

        txtZone.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtZone.setForeground(new java.awt.Color(0, 0, 51));
        getContentPane().add(txtZone, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, 200, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("Mobile Number:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, -1, -1));

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background1.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtLNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLNameActionPerformed

    private void txtFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFNameActionPerformed

    private void txtmanagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmanagerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmanagerActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        try{
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select *from user where username='"+username+"'");
                while(rs.next()){
                   
                    txtFName.setText(rs.getString("First_Name"));
                    txtMName.setText(rs.getString("Middle_Name"));
                    txtLName.setText(rs.getString("Last_Name"));
                    txtMobileNumber.setText(rs.getString("mobileNumber"));
                    txtStreet.setText(rs.getString("Street"));
                    txtZone.setText(rs.getString("Zone"));
                    txtmanager.setText(rs.getString("manager_ID"));
                    lUsername.setText(username);
                }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String fName=txtFName.getText();
        String mName=txtMName.getText();
        String lName=txtLName.getText();
        String mobileNumber=txtMobileNumber.getText();
        String street=txtStreet.getText();
        String zone=txtZone.getText();
        String manager=txtmanager.getText();
        if (fName.equals("")) {
            JOptionPane.showMessageDialog(null, "First Name field is required");
        } else if (mName.equals("")) {
            JOptionPane.showMessageDialog(null, "Middle Name field is required");
        } else if (lName.equals("")) {
            JOptionPane.showMessageDialog(null, "Last Name field is required");
        } else if (mobileNumber.equals("")) {
            JOptionPane.showMessageDialog(null, "Mobile number field is required");
        } else if (!mobileNumber.matches(mobileNumberPattern) || mobileNumber.length() != 11) {
            JOptionPane.showMessageDialog(null, "Mobile number field is invalid");
        } else if (street.equals("")) {
            JOptionPane.showMessageDialog(null, "Street field is required");
        } else if (zone.equals("")) {
            JOptionPane.showMessageDialog(null, "Zone field is required");
        } else if (manager.equals("")) {
            JOptionPane.showMessageDialog(null, "Manager ID field is required");
        }else{
            try{
               Connection con=ConnectionProvider.getCon();
               //First_Name,Middle_Name,Last_Name,mobileNumber,username,password,Street,Zone,salary
               PreparedStatement ps=con.prepareStatement("update user set First_Name=?,Middle_Name=?,Last_Name=?,mobileNumber=?,Street=?,Zone=?,manager_ID=? where username=?");
               ps.setString(1, fName);
               ps.setString(2, mName);
               ps.setString(3, lName);
               ps.setString(4, mobileNumber);
               ps.setString(5, street);
               ps.setString(6, zone);
               ps.setString(7, manager);
               ps.setString(8, username);
               ps.executeUpdate();
               JOptionPane.showMessageDialog(null, "Profile Updated Successfuly");
               setVisible(false);
               new Profile(username).setVisible(true);
               
               
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lUsername;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtMName;
    private javax.swing.JTextField txtMobileNumber;
    private javax.swing.JTextField txtStreet;
    private javax.swing.JTextField txtZone;
    private javax.swing.JTextField txtmanager;
    // End of variables declaration//GEN-END:variables
}
