/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pharmacy.management.system;


import doe.ConnectionProvider;
import doe.PharmacyUtils;
import static doe.PharmacyUtils.billPath;
import java.io.FileOutputStream;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.*;
import javax.swing.table.TableModel;

/**
 *
 * @author N A N A
 */
public class SellMedicine extends javax.swing.JFrame {
    public String  numberPattern ="^[0-9]*$";
    private int finalTotalPrice=0;
    private String billID="";
    private String username="";
    /**
     * Creates new form SellMedicine
     */
        public SellMedicine() {
        initComponents();
    }
    public SellMedicine(String tempUsername) {
        initComponents();
        username=tempUsername;
        setLocationRelativeTo(null);
        
    }
    private void DrugName(String nameOrUniqueID){
       DefaultTableModel model = (DefaultTableModel) drugTable.getModel(); 
       model.setRowCount(0);
       try{
           Connection con= ConnectionProvider.getCon();
           Statement st=con.createStatement();
           ResultSet rs=st.executeQuery("select * from Drug where Drug_Name like '"+nameOrUniqueID+"%'or Drug_ID like'"+nameOrUniqueID+"%'");
           while(rs.next()){
               model.addRow(new Object[]{rs.getString("drug_ID")+"- "+rs.getString("Drug_Name")});
           }
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
    }
    private void clearDrugFields(){
        txtDrugID.setText("");
        txtName.setText("");
        txtdrugmanfucture.setText("");
        txtPrice.setText("");
        txtNoOfUnits.setText("");
        txtTotalPrice.setText("");
    }
    public String getDrugID(String prefix){
       return prefix+ System.nanoTime();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtDrugID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNoOfUnits = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTotalPrice = new javax.swing.JTextField();
        txtdrugmanfucture = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        addCart = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        drugTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        cartTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        finalPrice = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Sell Medicine");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 279, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1010, -1));

        txtDrugID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDrugIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtDrugID, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 220, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("Price per Unit:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 90, 130, -1));

        txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPriceKeyReleased(evt);
            }
        });
        getContentPane().add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 130, 160, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setText("Number of Units:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 160, 140, -1));

        txtNoOfUnits.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNoOfUnitsKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNoOfUnitsKeyReleased(evt);
            }
        });
        getContentPane().add(txtNoOfUnits, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 190, 170, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 51));
        jLabel8.setText("Drug ID:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 90, -1));
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 220, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 51));
        jLabel9.setText(" Name:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 100, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("Drug manufacture:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, -1, -1));

        txtTotalPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalPriceActionPerformed(evt);
            }
        });
        getContentPane().add(txtTotalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 260, 210, -1));

        txtdrugmanfucture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdrugmanfuctureActionPerformed(evt);
            }
        });
        getContentPane().add(txtdrugmanfucture, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 210, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("Total Price:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, -1, -1));

        addCart.setText("Add to Cart");
        addCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCartActionPerformed(evt);
            }
        });
        getContentPane().add(addCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, -1, -1));

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 100, -1));

        drugTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Drug"
            }
        ));
        drugTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                drugTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(drugTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 430, 90));

        cartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug ID", "Drug Name", "Drug Manufacturer", "Price of Unit", "No of Units", "Total Price"
            }
        ));
        cartTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(cartTable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 520, 150));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("PRICE:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 540, 70, -1));

        finalPrice.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        finalPrice.setForeground(new java.awt.Color(0, 0, 51));
        finalPrice.setText("00");
        getContentPane().add(finalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 540, 30, 20));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/square-crossmark-red-button-close-exit-design-vector.jpg"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, 60, 50));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 51));
        jLabel7.setText("SEARCH");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background1.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDrugIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDrugIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDrugIDActionPerformed

    private void txtPriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txtPriceKeyReleased

    private void txtTotalPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalPriceActionPerformed

    private void txtdrugmanfuctureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdrugmanfuctureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdrugmanfuctureActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        DrugName("");
        txtDrugID.setEditable(false);
        txtName.setEditable(false);
        txtdrugmanfucture.setEditable(false);
        txtPrice.setEditable(false);
       // txtNoOfUnits.setEditable(false);
       // txtTotalPrice.setEditable(false);
    }//GEN-LAST:event_formComponentShown

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        String search=txtSearch.getText();
        DrugName(search);
    }//GEN-LAST:event_txtSearchKeyReleased

    private void drugTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drugTableMouseClicked
        // TODO add your handling code here:
        int index=drugTable.getSelectedRow();
        TableModel model =drugTable.getModel();
        String nameOrUniqueID=model.getValueAt(index, 0).toString();
        
        String DrugID[]=nameOrUniqueID.split("-",0);
        try{
           Connection con=ConnectionProvider.getCon();
           Statement st=con.createStatement();
           ResultSet rs=st.executeQuery("select *from drug where drug_ID="+DrugID[0]+"");
           while(rs.next()){
               txtDrugID.setText(DrugID[0]);
               txtName.setText(rs.getString("drug_name"));
               txtdrugmanfucture.setText(rs.getString("Drug_Manifacurer"));
               txtPrice.setText(rs.getString("price"));
               txtNoOfUnits.setText("");
               txtTotalPrice.setText("");
           }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_drugTableMouseClicked

    private void txtNoOfUnitsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoOfUnitsKeyReleased
        // TODO add your handling code here:
        String noOfUnits=txtNoOfUnits.getText();
        if(!noOfUnits.equals("")){
            String price=txtPrice.getText();
            if(!noOfUnits.matches(numberPattern)){
                JOptionPane.showMessageDialog(null, "Number of Units is  invalid");
            }
            int totalPrice=Integer.parseInt(noOfUnits)* Integer.parseInt(price);
            txtTotalPrice.setText(String.valueOf(totalPrice));
        }
        else{
            txtTotalPrice.setText("");
        }
    }//GEN-LAST:event_txtNoOfUnitsKeyReleased

    private void txtNoOfUnitsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoOfUnitsKeyPressed
        // TODO add your handling code here:
//         String noOfUnits=txtNoOfUnits.getText();
//        if(!noOfUnits.equals("")){
//            String price=txtPrice.getText();
//            if(!noOfUnits.matches(numberPattern)){
//                JOptionPane.showMessageDialog(null, "Number of Units is  invalid");
//            }
//            int totalPrice=Integer.parseInt(noOfUnits)* Integer.parseInt(price);
//            txtTotalPrice.setText(String.valueOf(totalPrice));
//        }
//        else{
//            txtTotalPrice.setText("");
//        }
    }//GEN-LAST:event_txtNoOfUnitsKeyPressed

    private void addCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCartActionPerformed
        // TODO add your handling code here:
        String noOfUnits=txtNoOfUnits.getText();
        String drugID=txtDrugID.getText();
        
        if(!noOfUnits.equals("")&&!drugID.equals("")){
            String drugName=txtName.getText();
            String drugmanf=txtdrugmanfucture.getText();
            String price=txtPrice.getText();
            String total=txtTotalPrice.getText();
            int checkStock=0;
            int checkDrugExist=0;
            
            try{
               Connection con=ConnectionProvider.getCon();
           Statement st=con.createStatement();
           ResultSet rs=st.executeQuery("select * from drug where drug_ID="+drugID+"");
            while(rs.next()){
                if(rs.getInt("stock")>=Integer.parseInt(noOfUnits)){
                    checkStock=1;
                }else{
                    JOptionPane.showMessageDialog(null, "Drug is out of stock. Only "+rs.getInt("stock")+"left");
                }
            }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            if(checkStock==1){
                DefaultTableModel dtm=(DefaultTableModel) cartTable.getModel();
                if(cartTable.getRowCount()!=0){
                    for (int i = 0; i < cartTable.getRowCount(); i++) {
                       if(Integer.parseInt(dtm.getValueAt(i, 0).toString())== Integer.parseInt(drugID)){
                           checkDrugExist=1;
                           JOptionPane.showMessageDialog(null, "medicine already exists in cart");
                       }
                    }
                }
                if(checkDrugExist==0){
                    dtm.addRow(new Object[]{drugID,drugName,drugmanf,price,noOfUnits,total});
                    finalTotalPrice=finalTotalPrice +Integer.parseInt(total);
                    finalPrice.setText(String.valueOf(finalTotalPrice));
                    JOptionPane.showMessageDialog(null, "Added Successfuly");
                }
                clearDrugFields();
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Number of Units and drug ID are required");
        }
    }//GEN-LAST:event_addCartActionPerformed

    private void cartTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartTableMouseClicked
        // TODO add your handling code here:
        int index=cartTable.getSelectedRow();
        int a =JOptionPane.showConfirmDialog(null, "Do you want to remove this medicine","select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            TableModel model=cartTable.getModel();
            String total=model.getValueAt(index, 5).toString();
            finalTotalPrice=finalTotalPrice-Integer.parseInt(total);
            finalPrice.setText(String.valueOf(finalTotalPrice));
            ((DefaultTableModel) cartTable.getModel()).removeRow(index);
            
        }
    }//GEN-LAST:event_cartTableMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SellMedicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCart;
    private javax.swing.JTable cartTable;
    private javax.swing.JTable drugTable;
    private javax.swing.JLabel finalPrice;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtDrugID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNoOfUnits;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTotalPrice;
    private javax.swing.JTextField txtdrugmanfucture;
    // End of variables declaration//GEN-END:variables
}
