/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pharmacy.management.system;

/**
 *
 * @author N A N A
 */
import doe.ConnectionProvider;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.*;
public class UpdateMedicine extends javax.swing.JFrame {

    /**
     * Creates new form UpdateMedicine
     */
    public String numberPattern="^[0-9]*$";
    public UpdateMedicine() {
        initComponents();
        setLocationRelativeTo(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtDrugID = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDrugType = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDrugManufacture = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtManufactureDate = new javax.swing.JTextField();
        txtExpireDate = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAddStock = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Update Medicine");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1110, 10));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("Drug ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        txtDrugID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDrugIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtDrugID, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 190, -1));

        jButton2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, -1, -1));

        jButton3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 90, 30));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("Drug Manufacture: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 140, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("Stock:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        txtStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockActionPerformed(evt);
            }
        });
        getContentPane().add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 220, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setText("Price per Unit:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 130, -1));

        txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPriceKeyReleased(evt);
            }
        });
        getContentPane().add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, 160, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 51));
        jLabel7.setText("Drug Type:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 80, -1));
        getContentPane().add(txtDrugType, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 170, -1));
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 220, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 51));
        jLabel9.setText(" Name:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 100, -1));

        txtDrugManufacture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDrugManufactureActionPerformed(evt);
            }
        });
        getContentPane().add(txtDrugManufacture, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 220, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 51));
        jLabel10.setText("Manfucture Date:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, -1, -1));
        getContentPane().add(txtManufactureDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 170, -1));
        getContentPane().add(txtExpireDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 170, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 51));
        jLabel11.setText("Expire Date:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 100, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("add Stock:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, -1, -1));

        txtAddStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddStockActionPerformed(evt);
            }
        });
        getContentPane().add(txtAddStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 210, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/square-crossmark-red-button-close-exit-design-vector.jpg"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 0, 60, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background1.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDrugIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDrugIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDrugIDActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          int checkDrugExist=0;
      String DrugID=txtDrugID.getText();
      if(DrugID.equals("")){
         JOptionPane.showMessageDialog(null, "drugID  field is required");
      }
      else {
          try{
               Connection con=ConnectionProvider.getCon();
               Statement st=con.createStatement();
              ResultSet rs=st.executeQuery("select *from drug where drug_ID='" + DrugID + "'");
               while(rs.next()){
                   txtDrugID.setEditable(false);
                   txtName.setText(rs.getString("Drug_Name"));
                   txtDrugManufacture.setText(rs.getString("Drug_Manifacurer"));
                   txtStock.setText(rs.getString("stock"));
                   txtPrice.setText(rs.getString("price"));
                  txtStock.setEditable(false);
                   txtDrugType.setText(rs.getString("Drug_Type"));
                    txtManufactureDate.setText(rs.getString("Manifacture_Date"));
                     txtExpireDate.setText(rs.getString("Expire_Date"));
                    checkDrugExist=1;
                   
                   
               }
          }
          catch(Exception e){
              JOptionPane.showMessageDialog(null, e);
          
          }
          if(checkDrugExist==0){
              JOptionPane.showMessageDialog(null,"DrugID does not exist");
          }
      }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
      String Drug_ID = txtDrugID.getText();
    String name = txtName.getText();
    String drugManufacture = txtDrugManufacture.getText();
    String stock = txtStock.getText();
    String price = txtPrice.getText();
    String addStock = txtAddStock.getText();
    String drugType = txtDrugType.getText();
    String manufactureDate = txtManufactureDate.getText();
    String expireDate = txtExpireDate.getText();
    int totalStock = 0;

    if (Drug_ID.equals("")) {
        JOptionPane.showMessageDialog(null, "DrugID field is required");
    } else if (name.equals("")) {
        JOptionPane.showMessageDialog(null, "Name field is required");
    } else if (drugManufacture.equals("")) {
        JOptionPane.showMessageDialog(null, "Drug Manufacture field is required");
    } else if (!addStock.matches(numberPattern)) {
        JOptionPane.showMessageDialog(null, "Add stock field is invalid");
    } else if (price.equals("")) {
        JOptionPane.showMessageDialog(null, "Price field is required");
    } else if (!price.matches(numberPattern)) {
        JOptionPane.showMessageDialog(null, "Price field is invalid");
    } else if (drugType.equals("")) {
        JOptionPane.showMessageDialog(null, "Drug Type field is required");
    } else if (manufactureDate.equals("")) {
        JOptionPane.showMessageDialog(null, "Manufacture date field is required");
    } else if (expireDate.equals("")) {
        JOptionPane.showMessageDialog(null, "Expire date field is required");
    } else {
        try {
            Connection con = ConnectionProvider.getCon();
            PreparedStatement ps = con.prepareStatement(
                    "UPDATE drug SET Drug_Name=?, Drug_Manifacurer=?, stock=?, price=?, drug_Type=?, Manifacture_Date=?, Expire_Date=? WHERE drug_ID=?");

            ps.setString(1, name);
            ps.setString(2, drugManufacture);

            if (!addStock.equals("")) {
                totalStock = Integer.parseInt(stock) + Integer.parseInt(addStock);
            } else {
                totalStock = Integer.parseInt(stock);
            }

            ps.setInt(3, totalStock);
            ps.setString(4, price);
            ps.setString(5, drugType);
            
            ps.setString(6, manufactureDate);
            ps.setString(7, expireDate);
            ps.setString(8, Drug_ID);

            int result = ps.executeUpdate();

            if (result > 0) {
                JOptionPane.showMessageDialog(null, "Medicine Updated Successfully");
                setVisible(false);
                new UpdateMedicine().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Update failed. Please check your inputs.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockActionPerformed

    private void txtPriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txtPriceKeyReleased

    private void txtDrugManufactureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDrugManufactureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDrugManufactureActionPerformed

    private void txtAddStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddStockActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateMedicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtAddStock;
    private javax.swing.JTextField txtDrugID;
    private javax.swing.JTextField txtDrugManufacture;
    private javax.swing.JTextField txtDrugType;
    private javax.swing.JTextField txtExpireDate;
    private javax.swing.JTextField txtManufactureDate;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
